name: build

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:

jobs:
  test-build:
    name: Test & Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ^1.16.1

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Test
      run: |
        go mod tidy -v
        go test -race ./...

    - name: Build
      run: go build ./...
